/**
 * Daily Reminders — system constants.
 * Keep business values centralized so later modules do not duplicate strings.
 */

var APP = {
  NAME: 'Daily Reminders',
  VERSION: '1.0.0',
  SCHEMA_VERSION: 1,
  TIMEZONE: 'Asia/Jerusalem'
};

var SHEETS = {
  REMINDERS: 'Reminders',
  INSTANCES: 'ReminderInstances',
  SETTINGS: 'Settings',
  LOGS: 'Logs'
};

var RECURRENCE_TYPES = {
  NONE: 'NONE',
  HOURLY_INTERVAL: 'HOURLY_INTERVAL',
  DAILY_INTERVAL: 'DAILY_INTERVAL',
  WEEKLY_DAYS: 'WEEKLY_DAYS'
};

var REMINDER_STATUS = {
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  ARCHIVED: 'ARCHIVED'
};

var INSTANCE_STATUS = {
  SCHEDULED: 'SCHEDULED',
  COMPLETED: 'COMPLETED',
  SNOOZED: 'SNOOZED',
  CANCELLED: 'CANCELLED',
  PAUSED: 'PAUSED',
  EXCEPTION: 'EXCEPTION'
};

var SYNC_STATUS = {
  NOT_SYNCED: 'NOT_SYNCED',
  SYNCED: 'SYNCED',
  SYNC_ERROR: 'SYNC_ERROR',
  DELETE_PENDING: 'DELETE_PENDING',
  DELETED: 'DELETED'
};

var SCRIPT_PROPERTY_KEYS = {
  SPREADSHEET_ID: 'DAILY_REMINDERS_SPREADSHEET_ID',
  CALENDAR_ID: 'DAILY_REMINDERS_CALENDAR_ID'
};

var DEFAULT_SETTINGS = {
  APP_NAME: APP.NAME,
  TIMEZONE: APP.TIMEZONE,
  DEFAULT_GENERATION_WINDOW: 30,
  UPCOMING_VIEW_DAYS: 7,
  MINIMUM_LEAD_MINUTES: 1,
  DEFAULT_NOTIFICATION_MINUTES: 0,
  CALENDAR_NAME: APP.NAME,
  APP_VERSION: APP.VERSION,
  SCHEMA_VERSION: String(APP.SCHEMA_VERSION),
  INITIALIZED: 'false'
};
